### ISSUE TITLE
More checkpoints?

### ISSUE THREAD

**Issue by TechInterMezzo** [yzGuu830/efficient-speech-codec#2]
The link only points to the 9kbps checkpoint. Will you also upload the checkpoints for the lower bitrates?

**Comment by yzGuu830** [comment]
@TechInterMezzo ESC can handle multi-level bitrates in a single model. The 9kbps checkpoint means the maximum allowed bitrate in that model is 9kbps. Basically it supports 1.5kbps ~ 9kbps (1.5kbps per stream, 6 streams in total) by setting `num_streams` argument.
