### ISSUE TITLE
error load model

### ISSUE THREAD

**Issue by sovse** [yzGuu830/efficient-speech-codec#3]
I'm getting an error when loading the model. How to fix it?

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_28494/746102269.py in <module>
      4 model_state_dict = torch.load(f"{model_pth}/model.pth")
      5 model = ESC(**config['model'])
----> 6 model.load_state_dict(model_state_dict)
      7 
      8 x, sr = librosa.load(librosa.example('libri1'), sr=16000, duration=9.995)

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1496         if len(error_msgs) > 0:
   1497             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
-> 1498                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1499         return _IncompatibleKeys(missing_keys, unexpected_keys)
   1500 

RuntimeError: Error(s) in loading state_dict for ESC:
	Missing key(s) in state_dict: "ft.window", "ift.window", "quantizers.0.vqs.0.embedding.weight", "quantizers.0.vqs.1.embedding.weight", "quantizers.0.vqs.2.embedding.weight", "quantizers.0.down_projs.0.weight", "quantizers.0.down_projs.1.weight", "quantizers.0.down_projs.2.weight", "quantizers.0.up_projs.0.weight", "quantizers.0.up_projs.1.weight", "quantizers.0.up_projs.2.weight", "quantizers.1.vqs.0.embedding.weight", "quantizers.1.vqs.1.embedding.weight", "quantizers.1.vqs.2.embedding.weight", "quantizers.1.down_projs.0.weight", "quantizers.1.down_projs.1.weight", "quantizers.1.down_projs.2.weight", "quantizers.1.up_projs.0.weight", "quantizers.1.up_projs.1.weight", "quantizers.1.up_projs.2.weight", "quantizers.2.vqs.0.embedding.weight", "quantizers.2.vqs.1.embedding.weight", "quantizers.2.vqs.2.embedding.weight", "quantizers.2.down_projs.0.weight", "quantizers.2.down_projs.1.weight", "quantizers.2.down_projs.2.weight", "quantizers.2.up_projs.0.weight", "quantizers.2.up_projs.1.weight", "quantizers.2.up_projs.2.weight", "quantizers.3.vqs.0.embedding.weight", "quantizers.3.vqs.1.embedding.weight", "quantizers.3.vqs.2.embedding.weight", "quantizers.3.down_projs.0.weight", "quantizers.3.down_projs.1.weight", "quantizers.3.down_projs.2.weight", "quantizers.3.up_projs.0.weight", "quantizers.3.up_projs.1.weight", "quantizers.3.up_projs.2.weight", "quantizers.4.vqs.0.embedding.weight", "quantizers.4.vqs.1.embedding.weight", "quantizers.4.vqs.2.embedding.weight", "quantizers.4.down_projs.0.weight", "quantizers.4.down_projs.1.weight", "quantizers.4.down_projs.2.weight", "quantizers.4.up_projs.0.weight", "quantizers.4.up_projs.1.weight", "quantizers.4.up_projs.2.weight", "quantizers.5.vqs.0.embedding.weight", "quantizers.5.vqs.1.embedding.weight", "quantizers.5.vqs.2.embedding.weight", "quantizers.5.down_projs.0.weight", "quantizers.5.down_projs.1.weight", "quantizers.5.down_projs.2.weight", "quantizers.5.up_projs.0.weight", "quantizers.5.up_projs.1.weight", "quantizers.5.up_projs.2.weight", "encoder.patch_embed.proj.weight", "encoder.patch_embed.proj.bias", "encoder.patch_embed.norm.weight", "encoder.patch_embed.norm.bias", "encoder.pre_nn.swint_blocks.0.norm1.weight", "encoder.pre_nn.swint_blocks.0.norm1.bias", "encoder.pre_nn.swint_blocks.0.attn.relative_position_bias_table", "encoder.pre_nn.swint_blocks.0.attn.relative_position_index", "encoder.pre_nn.swint_blocks.0.attn.qkv.weight", "encoder.pre_nn.swint_blocks.0.attn.qkv.bias", "encoder.pre_nn.swint_blocks.0.attn.proj.weight", "encoder.pre_nn.swint_blocks.0.attn.proj.bias", "encoder.pre_nn.swint_blocks.0.norm2.weight", "encoder.pre_nn.swint_blocks.0.norm2.bias", "encoder.pre_nn.swint_blocks.0.mlp.linear_1.weight", "encoder.pre_nn.swint_blocks.0.mlp.linear_1.bias", "encoder.pre_nn.swint_blocks.0.mlp.linear_2.weight", "encoder.pre_nn.swint_blocks.0.mlp.linear_2.bias", "encoder.pre_nn.swint_blocks.1.norm1.weight", "encoder.pre_nn.swint_blocks.1.norm1.bias", "encoder.pre_nn.swint_blocks.1.attn.relative_position_bias_table", "encoder.pre_nn.swint_blocks.1.attn.relative_position_index", "encoder.pre_nn.swint_blocks.1.attn.qkv.weight", "encoder.pre_nn.swint_blocks.1.attn.qkv.bias", "encoder.pre_nn.swint_blocks.1.attn.proj.weight", "encoder.pre_nn.swint_blocks.1.attn.proj.bias", "encoder.pre_nn.swint_blocks.1.norm2.weight", "encoder.pre_nn.swint_blocks.1.norm2.bias", "encoder.pre_nn.swint_blocks.1.mlp.linear_1.weight", "encoder.pre_nn.swint_blocks.1.mlp.linear_1.bias", "encoder.pre_nn.swint_blocks.1.mlp.linear_2.weight", "encoder.pre_nn.swint_blocks.1.mlp.linear_2.bias", "encoder.blocks.0.swint_blocks.0.norm1.weight", "encoder.blocks.0.swint_blocks.0.norm1.bias", "encoder.blocks.0.swint_blocks.0.attn.relative_position_bias_table", "encoder.blocks.0.swint_blocks.0.attn.relative_position_index", "encoder.blocks.0.swint_blocks.0.attn.qkv.weight", "encoder.blocks.0.swint_blocks.0.attn.qkv.bias", "encoder.blocks.0.swint_blocks.0.attn.proj.weight", "encoder.blocks.0.swint_blocks.0.attn.proj.bias", "encoder.blocks.0.swint_blocks.0.norm2.weight", "encoder.blocks.0.swint_blocks.0.norm2.bias", "encoder.blocks.0.swint_blocks.0.mlp.linear_1.weight", "encoder.blocks.0.swint_blocks.0.mlp.linear_1.bias", "encoder.blocks.0.swint_blocks.0.mlp.linear_2.weight", "encoder.blocks.0.swint_blocks.0.mlp.linear_2.bias", "encoder.blocks.0.swint_blocks.1.norm1.weight", "encoder.blocks.0.swint_blocks.1.norm1.bias", "encoder.blocks.0.swint_blocks.1.attn.relative_position_bias_table", "encoder.blocks.0.swint_blocks.1.attn.relative_position_index", "encoder.blocks.0.swint_blocks.1.attn.qkv.weight", "encoder.blocks.0.swint_blocks.1.attn.qkv.bias", "encoder.blocks.0.swint_blocks.1.attn.proj.weight", "encoder.blocks.0.swint_blocks.1.attn.proj.bias", "encoder.blocks.0.swint_blocks.1.norm2.weight", "encoder.blocks.0.swint_blocks.1.norm2.bias", "encoder.blocks.0.swint_blocks.1.mlp.linear_1.weight", "encoder.blocks.0.swint_blocks.1.mlp.linear_1.bias", "encoder.blocks.0.swint_blocks.1.mlp.linear_2.weight", "encoder.blocks.0.swint_blocks.1.mlp.linear_2.bias", "encoder.blocks.0.subsample.norm.weight", "encoder.blocks.0.subsample.norm.bias", "encoder.blocks.0.subsample.down.weight", "encoder.blocks.1.swint_blocks.0.norm1.weight", "encoder.blocks.1.swint_blocks.0.norm1.bias", "encoder.blocks.1.swint_blocks.0.attn.relative_position_bias_table", "encoder.blocks.1.swint_blocks.0.attn.relative_position_index", "encoder.blocks.1.swint_blocks.0.attn.qkv.weight", "encoder.blocks.1.swint_blocks.0.attn.qkv.bias", "encoder.blocks.1.swint_blocks.0.attn.proj.weight", "encoder.blocks.1.swint_blocks.0.attn.proj.bias", "encoder.blocks.1.swint_blocks.0.norm2.weight", "encoder.blocks.1.swint_blocks.0.norm2.bias", "encoder.blocks.1.swint_blocks.0.mlp.linear_1.weight", "encoder.blocks.1.swint_blocks.0.mlp.linear_1.bias", "encoder.blocks.1.swint_blocks.0.mlp.linear_2.weight", "encoder.blocks.1.swint_blocks.0.mlp.linear_2.bias", "encoder.blocks.1.swint_blocks.1.norm1.weight", "encoder.blocks.1.swint_blocks.1.norm1.bias", "encoder.blocks.1.swint_blocks.1.attn.relative_position_bias_table", "encoder.blocks.1.swint_blocks.1.attn.relative_position_index", "encoder.blocks.1.swint_blocks.1.attn.qkv.weight", "encoder.blocks.1.swint_blocks.1.attn.qkv.bias", "encoder.blocks.1.swint_blocks.1.attn.proj.weight", "encoder.blocks.1.swint_blocks.1.attn.proj.bias", "encoder.blocks.1.swint_blocks.1.norm2.weight", "encoder.blocks.1.swint_blocks.1.norm2.bias", "encoder.blocks.1.swint_blocks.1.mlp.linear_1.weight", "encoder.blocks.1.swint_blocks.1.mlp.linear_1.bias", "encoder.blocks.1.swint_blocks.1.mlp.linear_2.weight", "encoder.blocks.1.swint_blocks.1.mlp.linear_2.bias", "encoder.blocks.1.subsample.norm.weight", "encoder.blocks.1.subsample.norm.bias", "encoder.blocks.1.subsample.down.weight", "encoder.blocks.2.swint_blocks.0.norm1.weight", "encoder.blocks.2.swint_blocks.0.norm1.bias", "encoder.blocks.2.swint_blocks.0.attn.relative_position_bias_table", "encoder.blocks.2.swint_blocks.0.attn.relative_position_index", "encoder.blocks.2.swint_blocks.0.attn.qkv.weight", "encoder.blocks.2.swint_blocks.0.attn.qkv.bias", "encoder.blocks.2.swint_blocks.0.attn.proj.weight", "encoder.blocks.2.swint_blocks.0.attn.proj.bias", "encoder.blocks.2.swint_blocks.0.norm2.weight", "encoder.blocks.2.swint_blocks.0.norm2.bias", "encoder.blocks.2.swint_blocks.0.mlp.linear_1.weight", "encoder.blocks.2.swint_blocks.0.mlp.linear_1.bias", "encoder.blocks.2.swint_blocks.0.mlp.linear_2.weight", "encoder.blocks.2.swint_blocks.0.mlp.linear_2.bias", "encoder.blocks.2.swint_blocks.1.norm1.weight", "encoder.blocks.2.swint_blocks.1.norm1.bias", "encoder.blocks.2.swint_blocks.1.attn.relative_position_bias_table", "encoder.blocks.2.swint_blocks.1.attn.relative_position_index", "encoder.blocks.2.swint_blocks.1.attn.qkv.weight", "encoder.blocks.2.swint_blocks.1.attn.qkv.bias", "encoder.blocks.2.swint_blocks.1.attn.proj.weight", "encoder.blocks.2.swint_blocks.1.attn.proj.bias", "encoder.blocks.2.swint_blocks.1.norm2.weight", "encoder.blocks.2.swint_blocks.1.norm2.bias", "encoder.blocks.2.swint_blocks.1.mlp.linear_1.weight", "encoder.blocks.2.swint_blocks.1.mlp.linear_1.bias", "encoder.blocks.2.swint_blocks.1.mlp.linear_2.weight", "encoder.blocks.2.swint_blocks.1.mlp.linear_2.bias", "encoder.blocks.2.subsample.norm.weight", "encoder.blocks.2.subsample.norm.bias", "encoder.blocks.2.subsample.down.weight", "encoder.blocks.3.swint_blocks.0.norm1.weight", "encoder.blocks.3.swint_blocks.0.norm1.bias", "encoder.blocks.3.swint_blocks.0.attn.relative_position_bias_table", "encoder.blocks.3.swint_blocks.0.attn.relative_position_index", "encoder.blocks.3.swint_blocks.0.attn.qkv.weight", "encoder.blocks.3.swint_blocks.0.attn.qkv.bias", "encoder.blocks.3.swint_blocks.0.attn.proj.weight", "encoder.blocks.3.swint_blocks.0.attn.proj.bias", "encoder.blocks.3.swint_blocks.0.norm2.weight", "encoder.blocks.3.swint_blocks.0.norm2.bias", "encoder.blocks.3.swint_blocks.0.mlp.linear_1.weight", "encoder.blocks.3.swint_blocks.0.mlp.linear_1.bias", "encoder.blocks.3.swint_blocks.0.mlp.linear_2.weight", "encoder.blocks.3.swint_blocks.0.mlp.linear_2.bias", "encoder.blocks.3.swint_blocks.1.norm1.weight", "encoder.blocks.3.swint_blocks.1.norm1.bias", "encoder.blocks.3.swint_blocks.1.attn.relative_position_bias_table", "encoder.blocks.3.swint_blocks.1.attn.relative_position_index", "encoder.blocks.3.swint_blocks.1.attn.qkv.weight", "encoder.blocks.3.swint_blocks.1.attn.qkv.bias", "encoder.blocks.3.swint_blocks.1.attn.proj.weight", "encoder.blocks.3.swint_blocks.1.attn.proj.bias", "encoder.blocks.3.swint_blocks.1.norm2.weight", "encoder.blocks.3.swint_blocks.1.norm2.bias", "encoder.blocks.3.swint_blocks.1.mlp.linear_1.weight", "encoder.blocks.3.swint_blocks.1.mlp.linear_1.bias", "encoder.blocks.3.swint_blocks.1.mlp.linear_2.weight", "encoder.blocks.3.swint_blocks.1.mlp.linear_2.bias", "encoder.blocks.3.subsample.norm.weight", "encoder.blocks.3.subsample.norm.bias", "encoder.blocks.3.subsample.down.weight", "encoder.blocks.4.swint_blocks.0.norm1.weight", "encoder.blocks.4.swint_blocks.0.norm1.bias", "encoder.blocks.4.swint_blocks.0.attn.relative_position_bias_table", "encoder.blocks.4.swint_blocks.0.attn.relative_position_index", "encoder.blocks.4.swint_blocks.0.attn.qkv.weight", "encoder.blocks.4.swint_blocks.0.attn.qkv.bias", "encoder.blocks.4.swint_blocks.0.attn.proj.weight", "encoder.blocks.4.swint_blocks.0.attn.proj.bias", "encoder.blocks.4.swint_blocks.0.norm2.weight", "encoder.blocks.4.swint_blocks.0.norm2.bias", "encoder.blocks.4.swint_blocks.0.mlp.linear_1.weight", "encoder.blocks.4.swint_blocks.0.mlp.linear_1.bias", "encoder.blocks.4.swint_blocks.0.mlp.linear_2.weight", "encoder.blocks.4.swint_blocks.0.mlp.linear_2.bias", "encoder.blocks.4.swint_blocks.1.norm1.weight", "encoder.blocks.4.swint_blocks.1.norm1.bias", "encoder.blocks.4.swint_blocks.1.attn.relative_position_bias_table", "encoder.blocks.4.swint_blocks.1.attn.relative_position_index", "encoder.blocks.4.swint_blocks.1.attn.qkv.weight", "encoder.blocks.4.swint_blocks.1.attn.qkv.bias", "encoder.blocks.4.swint_blocks.1.attn.proj.weight", "encoder.blocks.4.swint_blocks.1.attn.proj.bias", "encoder.blocks.4.swint_blocks.1.norm2.weight", "encoder.blocks.4.swint_blocks.1.norm2.bias", "encoder.blocks.4.swint_blocks.1.mlp.linear_1.weight", "encoder.blocks.4.swint_blocks.1.mlp.linear_1.bias", "encoder.blocks.4.swint_blocks.1.mlp.linear_2.weight", "encoder.blocks.4.swint_blocks.1.mlp.linear_2.bias", "encoder.blocks.4.subsample.norm.weight", "encoder.blocks.4.subsample.norm.bias", "encoder.blocks.4.subsample.down.weight", "decoder.patch_deembed.de_proj1.weight", "decoder.patch_deembed.de_proj1.bias", "decoder.patch_deembed.de_proj2.weight", "decoder.patch_deembed.de_proj2.bias", "decoder.post_nn.swint_blocks.0.norm1.weight", "decoder.post_nn.swint_blocks.0.norm1.bias", "decoder.post_nn.swint_blocks.0.attn.relative_position_bias_table", "decoder.post_nn.swint_blocks.0.attn.relative_position_index", "decoder.post_nn.swint_blocks.0.attn.qkv.weight", "decoder.post_nn.swint_blocks.0.attn.qkv.bias", "decoder.post_nn.swint_blocks.0.attn.proj.weight", "decoder.post_nn.swint_blocks.0.attn.proj.bias", "decoder.post_nn.swint_blocks.0.norm2.weight", "decoder.post_nn.swint_blocks.0.norm2.bias", "decoder.post_nn.swint_blocks.0.mlp.linear_1.weight", "decoder.post_nn.swint_blocks.0.mlp.linear_1.bias", "decoder.post_nn.swint_blocks.0.mlp.linear_2.weight", "decoder.post_nn.swint_blocks.0.mlp.linear_2.bias", "decoder.post_nn.swint_blocks.1.norm1.weight", "decoder.post_nn.swint_blocks.1.norm1.bias", "decoder.post_nn.swint_blocks.1.attn.relative_position_bias_table", "decoder.post_nn.swint_blocks.1.attn.relative_position_index", "decoder.post_nn.swint_blocks.1.attn.qkv.weight", "decoder.post_nn.swint_blocks.1.attn.qkv.bias", "decoder.post_nn.swint_blocks.1.attn.proj.weight", "decoder.post_nn.swint_blocks.1.attn.proj.bias", "decoder.post_nn.swint_blocks.1.norm2.weight", "decoder.post_nn.swint_blocks.1.norm2.bias", "decoder.post_nn.swint_blocks.1.mlp.linear_1.weight", "decoder.post_nn.swint_blocks.1.mlp.linear_1.bias", "decoder.post_nn.swint_blocks.1.mlp.linear_2.weight", "decoder.post_nn.swint_blocks.1.mlp.linear_2.bias", "decoder.blocks.0.swint_blocks.0.norm1.weight", "decoder.blocks.0.swint_blocks.0.norm1.bias", "decoder.blocks.0.swint_blocks.0.attn.relative_position_bias_table", "decoder.blocks.0.swint_blocks.0.attn.relative_position_index", "decoder.blocks.0.swint_blocks.0.attn.qkv.weight", "decoder.blocks.0.swint_blocks.0.attn.qkv.bias", "decoder.blocks.0.swint_blocks.0.attn.proj.weight", "decoder.blocks.0.swint_blocks.0.attn.proj.bias", "decoder.blocks.0.swint_blocks.0.norm2.weight", "decoder.blocks.0.swint_blocks.0.norm2.bias", "decoder.blocks.0.swint_blocks.0.mlp.linear_1.weight", "decoder.blocks.0.swint_blocks.0.mlp.linear_1.bias", "decoder.blocks.0.swint_blocks.0.mlp.linear_2.weight", "decoder.blocks.0.swint_blocks.0.mlp.linear_2.bias", "decoder.blocks.0.swint_blocks.1.norm1.weight", "decoder.blocks.0.swint_blocks.1.norm1.bias", "decoder.blocks.0.swint_blocks.1.attn.relative_position_bias_table", "decoder.blocks.0.swint_blocks.1.attn.relative_position_index", "decoder.blocks.0.swint_blocks.1.attn.qkv.weight", "decoder.blocks.0.swint_blocks.1.attn.qkv.bias", "decoder.blocks.0.swint_blocks.1.attn.proj.weight", "decoder.blocks.0.swint_blocks.1.attn.proj.bias", "decoder.blocks.0.swint_blocks.1.norm2.weight", "decoder.blocks.0.swint_blocks.1.norm2.bias", "decoder.blocks.0.swint_blocks.1.mlp.linear_1.weight", "decoder.blocks.0.swint_blocks.1.mlp.linear_1.bias", "decoder.blocks.0.swint_blocks.1.mlp.linear_2.weight", "decoder.blocks.0.swint_blocks.1.mlp.linear_2.bias", "decoder.blocks.0.subsample.norm.weight", "decoder.blocks.0.subsample.norm.bias", "decoder.blocks.0.subsample.up.weight", "decoder.blocks.1.swint_blocks.0.norm1.weight", "decoder.blocks.1.swint_blocks.0.norm1.bias", "decoder.blocks.1.swint_blocks.0.attn.relative_position_bias_table", "decoder.blocks.1.swint_blocks.0.attn.relative_position_index", "decoder.blocks.1.swint_blocks.0.attn.qkv.weight", "decoder.blocks.1.swint_blocks.0.attn.qkv.bias", "decoder.blocks.1.swint_blocks.0.attn.proj.weight", "decoder.blocks.1.swint_blocks.0.attn.proj.bias", "decoder.blocks.1.swint_blocks.0.norm2.weight", "decoder.blocks.1.swint_blocks.0.norm2.bias", "decoder.blocks.1.swint_blocks.0.mlp.linear_1.weight", "decoder.blocks.1.swint_blocks.0.mlp.linear_1.bias", "decoder.blocks.1.swint_blocks.0.mlp.linear_2.weight", "decoder.blocks.1.swint_blocks.0.mlp.linear_2.bias", "decoder.blocks.1.swint_blocks.1.norm1.weight", "decoder.blocks.1.swint_blocks.1.norm1.bias", "decoder.blocks.1.swint_blocks.1.attn.relative_position_bias_table", "decoder.blocks.1.swint_blocks.1.attn.relative_position_index", "decoder.blocks.1.swint_blocks.1.attn.qkv.weight", "decoder.blocks.1.swint_blocks.1.attn.qkv.bias", "decoder.blocks.1.swint_blocks.1.attn.proj.weight", "decoder.blocks.1.swint_blocks.1.attn.proj.bias", "decoder.blocks.1.swint_blocks.1.norm2.weight", "decoder.blocks.1.swint_blocks.1.norm2.bias", "decoder.blocks.1.swint_blocks.1.mlp.linear_1.weight", "decoder.blocks.1.swint_blocks.1.mlp.linear_1.bias", "decoder.blocks.1.swint_blocks.1.mlp.linear_2.weight", "decoder.blocks.1.swint_blocks.1.mlp.linear_2.bias", "decoder.blocks.1.subsample.norm.weight", "decoder.blocks.1.subsample.norm.bias", "decoder.blocks.1.subsample.up.weight", "decoder.blocks.2.swint_blocks.0.norm1.weight", "decoder.blocks.2.swint_blocks.0.norm1.bias", "decoder.blocks.2.swint_blocks.0.attn.relative_position_bias_table", "decoder.blocks.2.swint_blocks.0.attn.relative_position_index", "decoder.blocks.2.swint_blocks.0.attn.qkv.weight", "decoder.blocks.2.swint_blocks.0.attn.qkv.bias", "decoder.blocks.2.swint_blocks.0.attn.proj.weight", "decoder.blocks.2.swint_blocks.0.attn.proj.bias", "decoder.blocks.2.swint_blocks.0.norm2.weight", "decoder.blocks.2.swint_blocks.0.norm2.bias", "decoder.blocks.2.swint_blocks.0.mlp.linear_1.weight", "decoder.blocks.2.swint_blocks.0.mlp.linear_1.bias", "decoder.blocks.2.swint_blocks.0.mlp.linear_2.weight", "decoder.blocks.2.swint_blocks.0.mlp.linear_2.bias", "decoder.blocks.2.swint_blocks.1.norm1.weight", "decoder.blocks.2.swint_blocks.1.norm1.bias", "decoder.blocks.2.swint_blocks.1.attn.relative_position_bias_table", "decoder.blocks.2.swint_blocks.1.attn.relative_position_index", "decoder.blocks.2.swint_blocks.1.attn.qkv.weight", "decoder.blocks.2.swint_blocks.1.attn.qkv.bias", "decoder.blocks.2.swint_blocks.1.attn.proj.weight", "decoder.blocks.2.swint_blocks.1.attn.proj.bias", "decoder.blocks.2.swint_blocks.1.norm2.weight", "decoder.blocks.2.swint_blocks.1.norm2.bias", "decoder.blocks.2.swint_blocks.1.mlp.linear_1.weight", "decoder.blocks.2.swint_blocks.1.mlp.linear_1.bias", "decoder.blocks.2.swint_blocks.1.mlp.linear_2.weight", "decoder.blocks.2.swint_blocks.1.mlp.linear_2.bias", "decoder.blocks.2.subsample.norm.weight", "decoder.blocks.2.subsample.norm.bias", "decoder.blocks.2.subsample.up.weight", "decoder.blocks.3.swint_blocks.0.norm1.weight", "decoder.blocks.3.swint_blocks.0.norm1.bias", "decoder.blocks.3.swint_blocks.0.attn.relative_position_bias_table", "decoder.blocks.3.swint_blocks.0.attn.relative_position_index", "decoder.blocks.3.swint_blocks.0.attn.qkv.weight", "decoder.blocks.3.swint_blocks.0.attn.qkv.bias", "decoder.blocks.3.swint_blocks.0.attn.proj.weight", "decoder.blocks.3.swint_blocks.0.attn.proj.bias", "decoder.blocks.3.swint_blocks.0.norm2.weight", "decoder.blocks.3.swint_blocks.0.norm2.bias", "decoder.blocks.3.swint_blocks.0.mlp.linear_1.weight", "decoder.blocks.3.swint_blocks.0.mlp.linear_1.bias", "decoder.blocks.3.swint_blocks.0.mlp.linear_2.weight", "decoder.blocks.3.swint_blocks.0.mlp.linear_2.bias", "decoder.blocks.3.swint_blocks.1.norm1.weight", "decoder.blocks.3.swint_blocks.1.norm1.bias", "decoder.blocks.3.swint_blocks.1.attn.relative_position_bias_table", "decoder.blocks.3.swint_blocks.1.attn.relative_position_index", "decoder.blocks.3.swint_blocks.1.attn.qkv.weight", "decoder.blocks.3.swint_blocks.1.attn.qkv.bias", "decoder.blocks.3.swint_blocks.1.attn.proj.weight", "decoder.blocks.3.swint_blocks.1.attn.proj.bias", "decoder.blocks.3.swint_blocks.1.norm2.weight", "decoder.blocks.3.swint_blocks.1.norm2.bias", "decoder.blocks.3.swint_blocks.1.mlp.linear_1.weight", "decoder.blocks.3.swint_blocks.1.mlp.linear_1.bias", "decoder.blocks.3.swint_blocks.1.mlp.linear_2.weight", "decoder.blocks.3.swint_blocks.1.mlp.linear_2.bias", "decoder.blocks.3.subsample.norm.weight", "decoder.blocks.3.subsample.norm.bias", "decoder.blocks.3.subsample.up.weight", "decoder.blocks.4.swint_blocks.0.norm1.weight", "decoder.blocks.4.swint_blocks.0.norm1.bias", "decoder.blocks.4.swint_blocks.0.attn.relative_position_bias_table", "decoder.blocks.4.swint_blocks.0.attn.relative_position_index", "decoder.blocks.4.swint_blocks.0.attn.qkv.weight", "decoder.blocks.4.swint_blocks.0.attn.qkv.bias", "decoder.blocks.4.swint_blocks.0.attn.proj.weight", "decoder.blocks.4.swint_blocks.0.attn.proj.bias", "decoder.blocks.4.swint_blocks.0.norm2.weight", "decoder.blocks.4.swint_blocks.0.norm2.bias", "decoder.blocks.4.swint_blocks.0.mlp.linear_1.weight", "decoder.blocks.4.swint_blocks.0.mlp.linear_1.bias", "decoder.blocks.4.swint_blocks.0.mlp.linear_2.weight", "decoder.blocks.4.swint_blocks.0.mlp.linear_2.bias", "decoder.blocks.4.swint_blocks.1.norm1.weight", "decoder.blocks.4.swint_blocks.1.norm1.bias", "decoder.blocks.4.swint_blocks.1.attn.relative_position_bias_table", "decoder.blocks.4.swint_blocks.1.attn.relative_position_index", "decoder.blocks.4.swint_blocks.1.attn.qkv.weight", "decoder.blocks.4.swint_blocks.1.attn.qkv.bias", "decoder.blocks.4.swint_blocks.1.attn.proj.weight", "decoder.blocks.4.swint_blocks.1.attn.proj.bias", "decoder.blocks.4.swint_blocks.1.norm2.weight", "decoder.blocks.4.swint_blocks.1.norm2.bias", "decoder.blocks.4.swint_blocks.1.mlp.linear_1.weight", "decoder.blocks.4.swint_blocks.1.mlp.linear_1.bias", "decoder.blocks.4.swint_blocks.1.mlp.linear_2.weight", "decoder.blocks.4.swint_blocks.1.mlp.linear_2.bias", "decoder.blocks.4.subsample.norm.weight", "decoder.blocks.4.subsample.norm.bias", "decoder.blocks.4.subsample.up.weight". 
	Unexpected key(s) in state_dict: "model_state_dict".

**Comment by yzGuu830** [comment]
@sovse thank you for bringing out this. It's now fixed in the latest version of the repository (see [this commit](https://github.com/yzGuu830/efficient-speech-codec/commit/46debf931f3c2af99002f1fdc3a017a8994474d7)).

Please pull the latest changes, and you should be able to load the model checkpoint correctly with the updated `example.ipynb`.

**Comment by sovse** [comment]
Thank you. It's working now.
