### ISSUE TITLE
Version of library in requirements.txt

### ISSUE THREAD

**Issue by xinkez** [yzGuu830/efficient-speech-codec#6]
Hi,

Thanks for sharing your codes.

I try to install your codes. However, without specifying the version in the requirements.txt file, the default installation is the latest version. There are compatibility issues during the installation process. Could you please specify the versions in the requirements.txt file? 

Thank you in advance.

**Comment by yzGuu830** [comment]
Hi, thank you for raising this. Just updated in this [commit](https://github.com/yzGuu830/efficient-speech-codec/commit/a131b0a9111c9d8efdfb242a086e2342ccb05eb9).

**Comment by xinkez** [comment]
> Hi, thank you for raising this. Just updated in this [commit](https://github.com/yzGuu830/efficient-speech-codec/commit/a131b0a9111c9d8efdfb242a086e2342ccb05eb9).

Thanks.
